[target.riscv64gc-unknown-none-elf]
rustflags = ['-Clink-arg=-Tsrc/arch/riscv64/linker.ld']

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
